name: Deploy Node.js App to Azure

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

env:
  AZURE_WEBAPP_NAME: bcf-detection-1759662837
  NODE_VERSION: '18.x'
  PYTHON_VERSION: '3.9'
  RESOURCE_GROUP: bcf-detection-rg

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Set up Python for BCF script
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Node.js dependencies
      run: npm install

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test BCF Detection Script
      run: python bcf_detecter.py

    - name: Test Node.js server locally
      run: |
        node server.js &
        sleep 5
        curl -f "http://localhost:3000/api/health" || exit 1
        pkill node
        echo "✅ Node.js server test passed!"

    - name: Create oryx build script
      run: |
        echo '#!/bin/bash' > oryx-build.sh
        echo 'echo "Installing Python dependencies..."' >> oryx-build.sh
        echo 'python3 -m pip install --upgrade pip' >> oryx-build.sh
        echo 'python3 -m pip install -r requirements.txt' >> oryx-build.sh
        chmod +x oryx-build.sh

    - name: Create deployment package
      run: |
        zip -r deploy.zip . -x "*.git*" "*.pyc" "__pycache__/*" "venv/*" ".venv/*" "*.zip"

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      run: |
        az webapp deployment source config-zip \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --src deploy.zip

    - name: Test deployment
      run: |
        sleep 45
        curl -f "https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/api/health" || exit 1
        echo "✅ Node.js deployment successful!"